<?php

namespace Database\Seeders\Other;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LiveConductorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('liveconductors')->insert([
            [
                'product_id'  => 1077,
                'title'       => 'حسابان نوبت عصر ثابتی',
                'date'        => '2023-06-18',
                'start_time'  => '14:00:00',
                'finish_time' => '19:50:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/hesaban',
            ],
            [
                'product_id'  => 1077,
                'title'       => 'حسابان نوبت عصر ثابتی',
                'date'        => '2023-06-19',
                'start_time'  => '14:00:00',
                'finish_time' => '19:50:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/hesaban',
            ],
            [
                'product_id'  => 1077,
                'title'       => 'حسابان نوبت عصر ثابتی',
                'date'        => '2023-06-20',
                'start_time'  => '14:00:00',
                'finish_time' => '19:50:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/hesaban',
            ],
            [
                'product_id'  => 1078,
                'title'       => 'زیست شناسی نوبت عصر کبیری راد',
                'date'        => '2023-06-18',
                'start_time'  => '14:00:00',
                'finish_time' => '19:50:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/zist',
            ],
            [
                'product_id'  => 1078,
                'title'       => 'زیست شناسی نوبت عصر کبیری راد',
                'date'        => '2023-06-19',
                'start_time'  => '14:00:00',
                'finish_time' => '19:50:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/zist',
            ],
            [
                'product_id'  => 1078,
                'title'       => 'زیست شناسی نوبت عصر کبیری راد',
                'date'        => '2023-06-20',
                'start_time'  => '14:00:00',
                'finish_time' => '19:50:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/zist',
            ],
            [
                'product_id'  => 1083,
                'title'       => 'زمین شناسی نوبت صبح کریمی',
                'date'        => '2023-06-21',
                'start_time'  => '07:00:00',
                'finish_time' => '13:20:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/zamin-karimi',
            ],
            [
                'product_id'  => 1083,
                'title'       => 'زمین شناسی نوبت صبح کریمی',
                'date'        => '2023-06-22',
                'start_time'  => '07:00:00',
                'finish_time' => '13:20:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/zamin-karimi',
            ],
            [
                'product_id'  => 1084,
                'title'       => 'زمین شناسی نوبت عصر نظیف',
                'date'        => '2023-06-21',
                'start_time'  => '14:00:00',
                'finish_time' => '19:50:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/zamin-nazif',
            ],
            [
                'product_id'  => 1084,
                'title'       => 'زمین شناسی نوبت عصر نظیف',
                'date'        => '2023-06-23',
                'start_time'  => '14:00:00',
                'finish_time' => '19:50:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/zamin-nazif',
            ],
            [
                'product_id'  => 1081,
                'title'       => 'هندسه نوبت عصر کبریایی',
                'date'        => '2023-06-21',
                'start_time'  => '14:00:00',
                'finish_time' => '19:50:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/hendese',
            ],
            [
                'product_id'  => 1081,
                'title'       => 'هندسه نوبت عصر کبریایی',
                'date'        => '2023-06-22',
                'start_time'  => '14:00:00',
                'finish_time' => '19:50:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/hendese',
            ],
            [
                'product_id'  => 1081,
                'title'       => 'هندسه نوبت عصر کبریایی',
                'date'        => '2023-06-23',
                'start_time'  => '14:00:00',
                'finish_time' => '19:50:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/hendese',
            ],
            [
                'product_id'  => 1080,
                'title'       => 'شیمی نوبت صبح حاجی سلیمانی',
                'date'        => '2023-06-24',
                'start_time'  => '07:00:00',
                'finish_time' => '13:20:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/shimi-hajisoleymani',
            ],
            [
                'product_id'  => 1080,
                'title'       => 'شیمی نوبت صبح حاجی سلیمانی',
                'date'        => '2023-06-25',
                'start_time'  => '07:00:00',
                'finish_time' => '13:20:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/shimi-hajisoleymani',
            ],
            [
                'product_id'  => 1080,
                'title'       => 'شیمی نوبت صبح حاجی سلیمانی',
                'date'        => '2023-06-26',
                'start_time'  => '07:00:00',
                'finish_time' => '13:20:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/shimi-hajisoleymani',
            ],
            [
                'product_id'  => 1071,
                'title'       => 'شیمی نوبت عصر توسلی فر',
                'date'        => '2023-06-24',
                'start_time'  => '14:00:00',
                'finish_time' => '19:50:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/shimi-tavasoli',
            ],
            [
                'product_id'  => 1071,
                'title'       => 'شیمی نوبت عصر توسلی فر',
                'date'        => '2023-06-25',
                'start_time'  => '14:00:00',
                'finish_time' => '19:50:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/shimi-tavasoli',
            ],
            [
                'product_id'  => 1071,
                'title'       => 'شیمی نوبت عصر توسلی فر',
                'date'        => '2023-06-26',
                'start_time'  => '14:00:00',
                'finish_time' => '19:50:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/shimi-tavasoli',
            ],
            [
                'product_id'  => 1079,
                'title'       => 'فیزیک نوبت صبح محمدی',
                'date'        => '2023-06-27',
                'start_time'  => '07:00:00',
                'finish_time' => '13:20:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/fizik-mohammadi',
            ],
            [
                'product_id'  => 1079,
                'title'       => 'فیزیک نوبت صبح محمدی',
                'date'        => '2023-06-28',
                'start_time'  => '07:00:00',
                'finish_time' => '13:20:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/fizik-mohammadi',
            ],
            [
                'product_id'  => 1079,
                'title'       => 'فیزیک نوبت صبح محمدی',
                'date'        => '2023-06-29',
                'start_time'  => '07:00:00',
                'finish_time' => '13:20:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/fizik-mohammadi',
            ],
            [
                'product_id'  => 1070,
                'title'       => 'فیزیک نوبت عصر یاری',
                'date'        => '2023-06-27',
                'start_time'  => '14:00:00',
                'finish_time' => '19:50:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/fizik-yari',
            ],
            [
                'product_id'  => 1070,
                'title'       => 'فیزیک نوبت عصر یاری',
                'date'        => '2023-06-28',
                'start_time'  => '14:00:00',
                'finish_time' => '19:50:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/fizik-yari',
            ],
            [
                'product_id'  => 1070,
                'title'       => 'فیزیک نوبت عصر یاری',
                'date'        => '2023-06-29',
                'start_time'  => '14:00:00',
                'finish_time' => '19:50:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/fizik-yari',
            ],
            [
                'product_id'  => 1067,
                'title'       => 'ریاضی تجربی نوبت عصر ثابتی',
                'date'        => '2023-06-30',
                'start_time'  => '14:00:00',
                'finish_time' => '19:50:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/riaziat-tajrobi',
            ],
            [
                'product_id'  => 1067,
                'title'       => 'ریاضی تجربی نوبت عصر ثابتی',
                'date'        => '2023-07-01',
                'start_time'  => '14:00:00',
                'finish_time' => '19:50:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/riaziat-tajrobi',
            ],
            [
                'product_id'  => 1067,
                'title'       => 'ریاضی تجربی نوبت عصر ثابتی',
                'date'        => '2023-07-02',
                'start_time'  => '14:00:00',
                'finish_time' => '19:50:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/riaziat-tajrobi',
            ],
            [
                'product_id'  => 1082,
                'title'       => 'گسسته نوبت عصر حسینی فرد',
                'date'        => '2023-06-30',
                'start_time'  => '14:00:00',
                'finish_time' => '19:50:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/gosaste',
            ],
            [
                'product_id'  => 1082,
                'title'       => 'گسسته نوبت عصر حسینی فرد',
                'date'        => '2023-07-01',
                'start_time'  => '14:00:00',
                'finish_time' => '19:50:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/gosaste',
            ],
            [
                'product_id'  => 1082,
                'title'       => 'گسسته نوبت عصر حسینی فرد',
                'date'        => '2023-07-02',
                'start_time'  => '14:00:00',
                'finish_time' => '19:50:00',
                'created_at'  => now(),
                'updated_at'  => now(),
                'live_link'   => 'https://www.skyroom.online/ch/alaa_tv/gosaste',
            ],
        ]);
    }
}
