<?php


namespace App\Classes;


use Config;
use Illuminate\Cache\RedisStore;

class AlaaRedisStore extends RedisStore
{
    public function put($key, $value, $seconds)
    {
        Config::set($key, $this->serialize($value));
        dump($key);
        return parent::put($key, $value, $seconds); // TODO: Change the autogenerated stub
    }

    public function get($key)
    {
        dump($key);
        $value = Config::get($key);

        if (isset($value)) {
            dd(2);
            return $this->unserialize($value);
        }
        dump(3);
        return parent::get($key); // TODO: Change the autogenerated stub
    }


}
